### ISSUE TITLE
Audio don't autoplay for next track when in background (Ionic app)

### ISSUE THREAD

**Issue by hbt272** [karbonn/Angular2-AudioComponent#2]
Hi!
I used this component in my Ionic 2 project. Every thing working well!
When I playing a playlist and press home button in android, the current playing still play. But the next track not play after current track finished.
Any help!

**Comment by hbt272** [comment]
It's not this component issue! It worked with cordova background component 
Thanks!

**Comment by hbt272** [comment]
It's not this component issue! It working fine with cordova background mode plugin!
Thanks!

**Comment by AAveline** [comment]
Ok and sorry for the late response !
