### ISSUE TITLE
How to start the projects ???

### ISSUE THREAD

**Issue by ppetrow** [karbonn/Angular2-AudioComponent#3]

**Comment by AAveline** [comment]
Hello,
You need to import the module:
Angular2AudioComponentModule

**Comment by ppetrow** [comment]
Hello my friend,

I import the module but it didn't work., Can you give me example of your project.

**Comment by ppetrow** [comment]
This is link of my project https://github.com/ppetrow/Angular2AudioComponent

**Comment by AAveline** [comment]
Hum, the path from your file is not right. try to put your file in the assets folder and copy/paste this link in your component: './assets/YOUR-FILE'
