### ISSUE TITLE
Doesn't build on angular6 production (--prod)

### ISSUE THREAD

**Issue by jfvilasAbanca** [karbonn/Angular2-AudioComponent#4]
Hi. Although I can use the component without a problem with regular builds, I'm obtaining this error

**ERROR in node_modules\angular2-audio-component\src\audio.component.d.ts.AudioComponent.html(3,10): : Property 'list' does not exist on type 'AudioComponent'**

when building for production. I think the error could be solved decoring 'list' as @Input (or just removing list).  Thanks in advance for this good job.

**Comment by AAveline** [comment]
Hi! It's fixed ;) Tell me if it doesn't work!

**Comment by jfvilasAbanca** [comment]
It's perfect. Thank you very much. Would you release a new version of the package in npmjs? Thanks in advance.

**Comment by AAveline** [comment]
Hi ! Sorry for the late response, the package has been bumped to @1.0.2 !

**Comment by jfvilasAbanca** [comment]
Successfully tested!! You can add "angular6" tag on npmjs if you want. Thank you very much.
